/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Subscriber } from "./Subscriber";
import { SubscriberCountArgs } from "./SubscriberCountArgs";
import { SubscriberFindManyArgs } from "./SubscriberFindManyArgs";
import { SubscriberFindUniqueArgs } from "./SubscriberFindUniqueArgs";
import { CreateSubscriberArgs } from "./CreateSubscriberArgs";
import { UpdateSubscriberArgs } from "./UpdateSubscriberArgs";
import { DeleteSubscriberArgs } from "./DeleteSubscriberArgs";
import { EmailLogFindManyArgs } from "../../emailLog/base/EmailLogFindManyArgs";
import { EmailLog } from "../../emailLog/base/EmailLog";
import { SubscriptionFindManyArgs } from "../../subscription/base/SubscriptionFindManyArgs";
import { Subscription } from "../../subscription/base/Subscription";
import { SubscriberService } from "../subscriber.service";
@graphql.Resolver(() => Subscriber)
export class SubscriberResolverBase {
  constructor(protected readonly service: SubscriberService) {}

  async _subscribersMeta(
    @graphql.Args() args: SubscriberCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Subscriber])
  async subscribers(
    @graphql.Args() args: SubscriberFindManyArgs
  ): Promise<Subscriber[]> {
    return this.service.subscribers(args);
  }

  @graphql.Query(() => Subscriber, { nullable: true })
  async subscriber(
    @graphql.Args() args: SubscriberFindUniqueArgs
  ): Promise<Subscriber | null> {
    const result = await this.service.subscriber(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Subscriber)
  async createSubscriber(
    @graphql.Args() args: CreateSubscriberArgs
  ): Promise<Subscriber> {
    return await this.service.createSubscriber({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Subscriber)
  async updateSubscriber(
    @graphql.Args() args: UpdateSubscriberArgs
  ): Promise<Subscriber | null> {
    try {
      return await this.service.updateSubscriber({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Subscriber)
  async deleteSubscriber(
    @graphql.Args() args: DeleteSubscriberArgs
  ): Promise<Subscriber | null> {
    try {
      return await this.service.deleteSubscriber(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [EmailLog], { name: "emailLogs" })
  async findEmailLogs(
    @graphql.Parent() parent: Subscriber,
    @graphql.Args() args: EmailLogFindManyArgs
  ): Promise<EmailLog[]> {
    const results = await this.service.findEmailLogs(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Subscription], { name: "subscriptions" })
  async findSubscriptions(
    @graphql.Parent() parent: Subscriber,
    @graphql.Args() args: SubscriptionFindManyArgs
  ): Promise<Subscription[]> {
    const results = await this.service.findSubscriptions(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
